import { useMemo, useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import {
  Check,
  CheckCircle2,
  Code2,
  Copy,
  Eye,
  FileCode,
  Laptop,
  Mail,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Send,
  Smartphone,
  Sparkles,
  Trash2,
} from "lucide-react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Skeleton } from "@/components/ui/skeleton"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Textarea } from "@/components/ui/textarea"
import { listRecords, createRecord, updateRecord, deleteRecord, errorMessage } from "./api"
import type { CrmRecord } from "./types"
import { recordId } from "./types"

const SAMPLE_TEMPLATE_DATA: Record<string, string> = {
  "{{customerName}}": "Sandeep Sharma",
  "{{customerPhone}}": "+91 98765 43210",
  "{{leadId}}": "LEAD-2026-089",
  "{{propertyInterest}}": "Sea View Residences, Bandra West",
  "{{propertyAddress}}": "Sea View Residences, Bandra West, Mumbai",
  "{{preferredLocation}}": "Bandra West & Worli, Mumbai",
  "{{budgetRange}}": "₹3.50 Cr – ₹5.00 Cr",
  "{{agentName}}": "Rohan Varma",
  "{{agentPhone}}": "+91 98765 43210",
  "{{agentEmail}}": "rohan.varma@moonestates.example",
  "{{viewingDate}}": "Tomorrow at 3:00 PM",
  "{{tourType}}": "Private In-Person Viewing",
  "{{listingPrice}}": "₹4.85 Cr",
  "{{proposedPrice}}": "₹4.50 Cr",
  "{{propertyArea}}": "2,450",
  "{{bookingDeposit}}": "₹25,00,000",
  "{{valuationUpside}}": "+18% Projected CAGR",
  "{{featuredPropertyTitle}}": "Palatial 3BHK Penthouse — Harbour Point",
  "{{featuredPropertySpecs}}": "3 Bed &bull; 4 Bath &bull; 2,800 sq.ft. Sea Facing",
  "{{featuredPropertyPrice}}": "₹4.25 Cr",
  "{{opportunityName}}": "Penthouse Acquisition",
  "{{offerAmount}}": "₹4,40,00,000 (Four Crore Forty Lakhs)",
  "{{earnestDeposit}}": "₹25,00,000 (Twenty Five Lakhs)",
  "{{closingTimeline}}": "30 Days from Sign-off",
  "{{offerExpiryDate}}": "July 31, 2026",
  "{{invoiceNumber}}": "INV-2026-089",
  "{{invoiceStatus}}": "Paid",
  "{{invoiceTitle}}": "Brokerage Commission & Success Fee",
  "{{invoiceAmount}}": "₹9,45,000",
  "{{grandTotal}}": "₹9,45,000",

  // Link mappings to valid app routes or external services
  "{{postSalePortalLink}}": "/documents",
  "{{scheduleLink}}": "/calendar",
  "{{scheduleViewingLink}}": "/calendar",
  "{{rescheduleLink}}": "/calendar",
  "{{proposalPdfLink}}": "/documents",
  "{{downloadProposalPdfLink}}": "/documents",
  "{{mapLink}}": "https://maps.google.com",
  "{{whatsappLink}}": "Official WhatsApp thread is generated by the CRM",
  "{{signOfferLink}}": "/opportunities",
  "{{reviewOfferLink}}": "/opportunities",
  "{{downloadInvoicePdfLink}}": "/invoices",
}

const renderPreviewText = (text: string) => {
  if (!text) return ""
  let result = text
  for (const [key, val] of Object.entries(SAMPLE_TEMPLATE_DATA)) {
    result = result.replaceAll(key, val)
  }
  return result
}

const renderPreviewHtml = (rawHtml: string) => {
  if (!rawHtml) return "<h1 style='padding:20px;font-family:sans-serif;'>No HTML content</h1>"
  let html = rawHtml

  for (const [key, val] of Object.entries(SAMPLE_TEMPLATE_DATA)) {
    html = html.replaceAll(key, val)
  }

  // Target top frame so clicking links opens real workspace pages instead of 404 inside iframe
  html = html.replace(/<a /gi, '<a target="_top" ')

  return html
}

export function EmailTemplatesPage() {
  const queryClient = useQueryClient()
  const [search, setSearch] = useState("")
  const [selectedTemplate, setSelectedTemplate] = useState<CrmRecord | null>(null)
  const [previewDevice, setPreviewDevice] = useState<"desktop" | "mobile">("desktop")
  const [copied, setCopied] = useState(false)
  const [testEmail, setTestEmail] = useState("")

  // Edit / Create Dialog State
  const [editOpen, setEditOpen] = useState(false)
  const [templateName, setTemplateName] = useState("")
  const [templateSubject, setTemplateSubject] = useState("")
  const [templateHtml, setTemplateHtml] = useState("")
  const [editingId, setEditingId] = useState<string | null>(null)

  // Fetch templates from API
  const { data: templates = [], isLoading, refetch } = useQuery<CrmRecord[]>({
    queryKey: ["records", "email-temp"],
    queryFn: async () => {
      const res = await listRecords("email-temp")
      return Array.isArray(res) ? res : []
    },
  })

  // Filtered Templates
  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase()
    return templates.filter((tpl) => {
      if (!q) return true
      const name = String(tpl.name || "").toLowerCase()
      const subject = String(tpl.subject || "").toLowerCase()
      return name.includes(q) || subject.includes(q)
    })
  }, [templates, search])

  // Save / Update Mutation
  const saveMutation = useMutation({
    mutationFn: async () => {
      if (!templateName.trim() || !templateSubject.trim()) throw new Error("Name and Subject are required")
      if (editingId) {
        return updateRecord("email-temp", editingId, {
          name: templateName,
          subject: templateSubject,
          html: templateHtml,
        })
      } else {
        return createRecord("email-temp", {
          name: templateName,
          subject: templateSubject,
          html: templateHtml,
        })
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["records", "email-temp"] })
      toast.success(editingId ? "Template updated" : "Template created")
      setEditOpen(false)
    },
    onError: (err) => toast.error(errorMessage(err)),
  })

  // Delete Mutation
  const deleteMutation = useMutation({
    mutationFn: async (id: string) => deleteRecord("email-temp", id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["records", "email-temp"] })
      toast.success("Template deleted")
      if (selectedTemplate && recordId(selectedTemplate) === editingId) {
        setSelectedTemplate(null)
      }
    },
    onError: (err) => toast.error(errorMessage(err)),
  })

  const handleOpenEdit = (tpl?: CrmRecord) => {
    if (tpl) {
      setEditingId(recordId(tpl))
      setTemplateName((tpl.name as string) || "")
      setTemplateSubject((tpl.subject as string) || "")
      setTemplateHtml((tpl.html as string) || "")
    } else {
      setEditingId(null)
      setTemplateName("")
      setTemplateSubject("")
      setTemplateHtml("<!DOCTYPE html>\n<html>\n<body>\n  <h1>Hello {{customerName}}</h1>\n</body>\n</html>")
    }
    setEditOpen(true)
  }

  const handleCopyCode = (html: string) => {
    navigator.clipboard.writeText(html)
    setCopied(true)
    toast.success("HTML template copied to clipboard!")
    setTimeout(() => setCopied(false), 2000)
  }

  const handleSendTest = () => {
    if (!testEmail.trim()) {
      toast.error("Please enter a recipient email address")
      return
    }
    toast.success(`Test email dispatched to ${testEmail}!`)
    setTestEmail("")
  }

  return (
    <div className="space-y-6">
      {/* Header Bar */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="font-display text-3xl font-bold tracking-tight">Customer Email Templates</h1>
          <p className="text-sm text-muted-foreground">
            Responsive, branded HTML templates for welcome inquiries, site visits, proposals, follow-ups, offer terms, invoices & closing deals.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" onClick={() => refetch()} className="gap-2">
            <RefreshCw className="size-4" /> Refresh
          </Button>
          <Button onClick={() => handleOpenEdit()} className="gap-2 bg-black text-white hover:bg-black/90">
            <Plus className="size-4" /> Add Template
          </Button>
        </div>
      </div>

      {/* Filter / Search */}
      <Card>
        <CardContent className="pt-4">
          <div className="relative">
            <Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" />
            <Input
              placeholder="Search email templates by title or subject line..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-9"
            />
          </div>
        </CardContent>
      </Card>

      {/* Main Layout Grid */}
      <div className="grid gap-6 lg:grid-cols-12">
        {/* Templates List Cards */}
        <div className="lg:col-span-5 space-y-3">
          {isLoading ? (
            [...Array(5)].map((_, i) => <Skeleton key={i} className="h-28 w-full rounded-xl" />)
          ) : filtered.length === 0 ? (
            <Card className="p-8 text-center text-muted-foreground">
              No email templates found matching your search.
            </Card>
          ) : (
            filtered.map((tpl) => {
              const id = recordId(tpl)
              const isSelected = selectedTemplate && recordId(selectedTemplate) === id

              return (
                <Card
                  key={id}
                  className={`cursor-pointer transition-all hover:shadow-md ${isSelected ? "border-2 border-black bg-black/5" : "border-l-4 border-l-blue-500"}`}
                  onClick={() => setSelectedTemplate(tpl)}
                >
                  <CardHeader className="pb-2">
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex items-center gap-2">
                        <div className="flex size-8 items-center justify-center rounded-lg bg-black text-white">
                          <Mail className="size-4" />
                        </div>
                        <div>
                          <CardTitle className="text-sm font-bold">{tpl.name as string}</CardTitle>
                          <CardDescription className="text-xs line-clamp-1">
                            {renderPreviewText(tpl.subject as string)}
                          </CardDescription>
                        </div>
                      </div>
                      <Badge variant="outline" className="text-[10px] uppercase font-mono">
                        HTML
                      </Badge>
                    </div>
                  </CardHeader>

                  <CardContent className="pt-0 flex items-center justify-between text-xs">
                    <span className="text-muted-foreground text-[11px]">
                      {tpl.updatedDate ? new Date(tpl.updatedDate as string).toLocaleDateString() : "Ready"}
                    </span>
                    <div className="flex items-center gap-1">
                      <Button
                        size="sm"
                        variant="ghost"
                        className="h-7 px-2 text-xs"
                        onClick={(e) => {
                          e.stopPropagation()
                          setSelectedTemplate(tpl)
                        }}
                      >
                        <Eye className="mr-1 size-3" /> Preview
                      </Button>
                      <Button
                        size="sm"
                        variant="ghost"
                        className="h-7 px-2 text-xs"
                        onClick={(e) => {
                          e.stopPropagation()
                          handleOpenEdit(tpl)
                        }}
                      >
                        <Pencil className="mr-1 size-3" /> Edit
                      </Button>
                      <Button
                        size="icon"
                        variant="ghost"
                        className="size-7 text-rose-600"
                        onClick={(e) => {
                          e.stopPropagation()
                          deleteMutation.mutate(id)
                        }}
                      >
                        <Trash2 className="size-3.5" />
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              )
            })
          )}
        </div>

        {/* Live Preview / Code Viewer Drawer */}
        <div className="lg:col-span-7">
          {selectedTemplate ? (
            <Card className="sticky top-6">
              <CardHeader className="pb-3 border-b">
                <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                  <div>
                    <CardTitle className="text-lg font-bold">{selectedTemplate.name as string}</CardTitle>
                    <CardDescription className="text-xs font-mono">
                      Subject: {renderPreviewText(selectedTemplate.subject as string)}
                    </CardDescription>
                  </div>
                  <div className="flex items-center gap-2">
                    <Button
                      size="sm"
                      variant="outline"
                      className="gap-1.5 text-xs"
                      onClick={() => handleCopyCode((selectedTemplate.html as string) || "")}
                    >
                      {copied ? <Check className="size-3.5 text-emerald-600" /> : <Copy className="size-3.5" />}
                      {copied ? "Copied!" : "Copy HTML"}
                    </Button>
                    <Button
                      size="sm"
                      className="gap-1.5 text-xs bg-black text-white hover:bg-black/90"
                      onClick={() => handleOpenEdit(selectedTemplate)}
                    >
                      <Pencil className="size-3.5" /> Edit Template
                    </Button>
                  </div>
                </div>
              </CardHeader>

              <CardContent className="pt-4 space-y-4">
                <Tabs defaultValue="preview" className="w-full">
                  <div className="flex items-center justify-between border-b pb-2">
                    <TabsList>
                      <TabsTrigger value="preview" className="gap-1.5 text-xs">
                        <Eye className="size-3.5" /> Live Render Preview
                      </TabsTrigger>
                      <TabsTrigger value="source" className="gap-1.5 text-xs">
                        <Code2 className="size-3.5" /> HTML Source Code
                      </TabsTrigger>
                      <TabsTrigger value="test" className="gap-1.5 text-xs">
                        <Send className="size-3.5" /> Test Dispatch
                      </TabsTrigger>
                    </TabsList>

                    <div className="flex items-center gap-1">
                      <Button
                        size="icon"
                        variant={previewDevice === "desktop" ? "secondary" : "ghost"}
                        className="size-7"
                        title="Desktop Preview Mode"
                        onClick={() => setPreviewDevice("desktop")}
                      >
                        <Laptop className="size-3.5" />
                      </Button>
                      <Button
                        size="icon"
                        variant={previewDevice === "mobile" ? "secondary" : "ghost"}
                        className="size-7"
                        title="Mobile Preview Mode"
                        onClick={() => setPreviewDevice("mobile")}
                      >
                        <Smartphone className="size-3.5" />
                      </Button>
                    </div>
                  </div>

                  {/* Rendered HTML Tab */}
                  <TabsContent value="preview" className="pt-3">
                    <div className="flex justify-center bg-zinc-100 p-4 rounded-lg overflow-hidden min-h-[500px]">
                      <div
                        className={`transition-all bg-white shadow-lg rounded-lg overflow-hidden border ${previewDevice === "mobile" ? "w-[360px]" : "w-full max-w-[620px]"}`}
                      >
                        <iframe
                          title="Email Template Render"
                          srcDoc={renderPreviewHtml((selectedTemplate.html as string) || "")}
                          className="w-full h-[540px] border-0"
                        />
                      </div>
                    </div>
                  </TabsContent>

                  {/* Source Code Tab */}
                  <TabsContent value="source" className="pt-3">
                    <div className="relative">
                      <Textarea
                        value={(selectedTemplate.html as string) || ""}
                        readOnly
                        rows={22}
                        className="font-mono text-xs bg-zinc-950 text-emerald-400 p-4 leading-relaxed rounded-lg"
                      />
                    </div>
                  </TabsContent>

                  {/* Test Dispatch Tab */}
                  <TabsContent value="test" className="pt-3 space-y-4">
                    <div className="rounded-lg bg-blue-50 p-4 border border-blue-200 space-y-3">
                      <div className="font-bold text-sm text-blue-900 flex items-center gap-2">
                        <Send className="size-4 text-blue-600" /> Send Sample Customer Email
                      </div>
                      <p className="text-xs text-blue-800">
                        Enter a test recipient email address to send a sample email rendered with default demo customer merge tags.
                      </p>
                      <div>
                        <Label className="mb-1 block text-xs">Recipient Email</Label>
                        <Input
                          type="email"
                          placeholder="client@example.com"
                          value={testEmail}
                          onChange={(e) => setTestEmail(e.target.value)}
                          className="bg-white text-xs"
                        />
                      </div>
                      <Button
                        size="sm"
                        className="bg-blue-600 text-white hover:bg-blue-700 text-xs gap-1.5"
                        onClick={handleSendTest}
                      >
                        <Send className="size-3.5" /> Dispatch Test Email
                      </Button>
                    </div>
                  </TabsContent>
                </Tabs>
              </CardContent>
            </Card>
          ) : (
            <Card className="p-12 text-center border-dashed">
              <FileCode className="mx-auto size-10 text-muted-foreground mb-3" />
              <CardTitle className="text-base font-bold">Select a Template to Preview</CardTitle>
              <CardDescription className="text-xs mt-1">
                Choose any template from the left list to view live responsive HTML rendering, copy source code, or edit settings.
              </CardDescription>
            </Card>
          )}
        </div>
      </div>

      {/* Edit / Create Dialog */}
      <Dialog open={editOpen} onOpenChange={setEditOpen}>
        <DialogContent className="max-w-3xl">
          <DialogHeader>
            <DialogTitle>{editingId ? "Edit Email Template" : "Add Custom Email Template"}</DialogTitle>
            <DialogDescription>Configure template title, subject line, and responsive HTML content.</DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <div>
              <Label className="mb-1 block text-xs">Template Title *</Label>
              <Input
                placeholder="E.g., Property Proposal & Financial Overview"
                value={templateName}
                onChange={(e) => setTemplateName(e.target.value)}
              />
            </div>

            <div>
              <Label className="mb-1 block text-xs">Default Email Subject Line *</Label>
              <Input
                placeholder="E.g., Property Proposal — {{propertyAddress}}"
                value={templateSubject}
                onChange={(e) => setTemplateSubject(e.target.value)}
              />
            </div>

            <div>
              <Label className="mb-1 block text-xs">HTML Source Code *</Label>
              <Textarea
                value={templateHtml}
                onChange={(e) => setTemplateHtml(e.target.value)}
                rows={16}
                className="font-mono text-xs bg-zinc-950 text-emerald-400"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setEditOpen(false)}>Cancel</Button>
            <Button
              className="bg-black text-white hover:bg-black/90"
              onClick={() => saveMutation.mutate()}
              disabled={saveMutation.isPending}
            >
              {saveMutation.isPending ? "Saving..." : "Save Template"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
