import {
  BadgeIndianRupee,
  BarChart3,
  Building2,
  CalendarDays,
  CheckSquare2,
  ContactRound,
  CreditCard,
  FileCheck2,
  FileText,
  FolderKanban,
  Image,
  Landmark,
  Layers3,
  Mail,
  MailOpen,
  Megaphone,
  MessageCircle,
  Phone,
  PlugZap,
  ReceiptText,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  UserRoundCog,
  UsersRound,
  Video,
} from "lucide-react"
import type { ModuleConfig } from "./types"

export const modules: ModuleConfig[] = [
  {
    key: "conversations",
    label: "Conversations",
    singular: "Conversation",
    path: "/conversations",
    endpoint: "conversations",
    icon: MessageCircle,
    group: "Workspace",
    readOnly: true,
    fields: [{ key: "status", label: "Status" }],
  },
  {
    key: "meta-acquisition",
    label: "Meta Acquisition",
    singular: "Meta Campaign",
    path: "/meta-acquisition",
    endpoint: "meta/acquisition",
    icon: Megaphone,
    group: "Workspace",
    readOnly: true,
    fields: [{ key: "campaign", label: "Campaign" }],
  },
  {
    key: "leads",
    label: "Leads",
    singular: "Lead",
    path: "/leads",
    endpoint: "lead",
    icon: Sparkles,
    group: "Workspace",
    addMany: true,
    fields: [
      { key: "leadName", label: "Name", required: true },
      { key: "leadEmail", label: "Email", type: "email" },
      { key: "leadPhoneNumber", label: "Phone", type: "phone" },
      { key: "leadAddress", label: "Property or mailing address", type: "textarea", table: false },
      { key: "leadStatus", label: "Status", type: "select", options: ["New", "Attempting Contact", "Contacted", "Qualified", "Appointment", "Offer Made", "Converted", "Closed Lost"] },
      { key: "priority", label: "Priority", type: "select", options: ["Urgent", "High", "Medium", "Low"] },
      { key: "leadSource", label: "Source", type: "select", options: ["Cold Call", "Direct Mail", "Website", "Referral", "Driving for Dollars", "PPC", "SEO", "Social Media", "List Import", "API", "Other"] },
      { key: "nextFollowUpDate", label: "Next Follow-Up" },
      { key: "assignedTo", label: "Assigned agent", type: "select", options: ["MooN Estates", "Sandeep Kumar (Admin)", "Senior Advisor", "Sales Lead", "Unassigned"] },
    ],
  },
  {
    key: "followups",
    label: "Follow-Ups",
    singular: "Follow-Up",
    path: "/followups",
    endpoint: "lead-followup",
    icon: CalendarDays,
    group: "Workspace",
    fields: [
      { key: "leadId", label: "Lead" },
      { key: "followUpType", label: "Type", type: "select", options: ["call", "site_visit", "whatsapp", "email", "meeting", "quote", "other"] },
      { key: "followUpDate", label: "Scheduled Date/Time" },
      { key: "priority", label: "Priority", type: "select", options: ["urgent", "high", "medium", "low"] },
      { key: "status", label: "Status", type: "select", options: ["pending", "completed", "cancelled", "overdue"] },
      { key: "notes", label: "Objective / Notes", type: "textarea" },
      { key: "outcome", label: "Outcome Notes", type: "textarea" },
    ],
  },
  {
    key: "contacts",
    label: "Contacts",
    singular: "Contact",
    path: "/contacts",
    endpoint: "contact",
    icon: ContactRound,
    group: "Workspace",
    addMany: true,
    fields: [
      { key: "fullName", label: "Full name", required: true },
      { key: "email", label: "Email", type: "email" },
      { key: "phone", label: "Phone", type: "phone" },
      { key: "title", label: "Title", type: "select", options: ["Buyer", "Seller", "Developer Representative", "Investor", "Broker", "Tenant"] },
      { key: "physicalAddress", label: "Address", type: "textarea" },
      { key: "interestProperty", label: "Property interests", type: "textarea", description: "JSON or a short description of preferred properties.", table: false },
      { key: "quotes", label: "Related quotes", type: "textarea", table: false },
    ],
  },
  {
    key: "properties",
    label: "Properties",
    singular: "Property",
    path: "/properties",
    endpoint: "property",
    icon: Building2,
    group: "Workspace",
    addMany: true,
    fields: [
      { key: "propertyType", label: "Property type", type: "select", required: true, options: ["Apartment", "Villa", "Penthouse", "Commercial", "Land", "Single Family", "Multi Family", "Condo", "Townhouse", "Other"] },
      { key: "title", label: "Property Title", required: true },
      { key: "builder", label: "Builder / Developer", required: true },
      { key: "propertyAddress", label: "Property Address (Used for Map)", required: true, type: "textarea" },
      { key: "location", label: "Micro-Market / Location" },
      { key: "listingPrice", label: "Listing price", type: "currency" },
      { key: "towerName", label: "Tower Name" },
      { key: "totalFloors", label: "Total Floors in Building (Important for 3D Tower)", type: "number" },
      { key: "floorNumber", label: "Property Floor Level", type: "number" },
      { key: "unitNumber", label: "Unit Number" },
      { key: "bedrooms", label: "Bedrooms (BHK)", type: "number" },
      { key: "carpetArea", label: "Carpet Area (sq.ft.)", type: "number" },
      { key: "facing", label: "Facing", type: "select", options: ["East", "North-East", "North", "West", "South-East", "North-West", "South", "South-West"] },
      { key: "status", label: "Status", type: "select", options: ["Available", "Under Offer", "Sold"] },
      { key: "reraId", label: "RERA Registration Number" },
      { key: "propertyPhotos", label: "Property photos (All)", type: "textarea", table: false },
      { key: "photoLivingRoom", label: "Living Room Photo", type: "textarea", table: false },
      { key: "photoKitchen", label: "Kitchen Photo", type: "textarea", table: false },
      { key: "photoRoom1", label: "Bedroom 1 Photo", type: "textarea", table: false },
      { key: "photoRoom2", label: "Bedroom 2 Photo", type: "textarea", table: false },
      { key: "photoWashroom", label: "Washroom Photo", type: "textarea", table: false },
      { key: "photoBalcony", label: "Balcony Photo", type: "textarea", table: false },
      { key: "virtualToursOrVideos", label: "Virtual tours or videos", type: "textarea", table: false },
      { key: "floorPlans", label: "Floor plans", type: "textarea", table: false },
      { key: "propertyDocuments", label: "Property documents", type: "textarea", table: false },
    ],
  },

  {
    key: "opportunities",
    label: "Opportunities",
    singular: "Opportunity",
    path: "/opportunities",
    endpoint: "opportunity",
    icon: BarChart3,
    group: "Workspace",
    addMany: true,
    fields: [
      { key: "opportunityName", label: "Opportunity", required: true },
      { key: "accountName", label: "Account", type: "select", options: ["Oberoi Realty", "Prestige Group", "Godrej Properties", "Harbourline Holdings", "Northstar Living", "Crescent Family Office", "DLF Limited"] },
      { key: "amount", label: "Deal value", type: "currency" },
      { key: "stage", label: "Stage", type: "select", required: true, options: ["Prospecting", "Qualification", "Proposal", "Negotiation", "Closed Won", "Closed Lost"] },
      { key: "probability", label: "Probability", type: "number", min: 0, max: 100, step: 5 },
      { key: "closeDate", label: "Close date", type: "date" },
      { key: "leadSource", label: "Lead source", type: "select", options: ["Cold Call", "Direct Mail", "Website", "Referral", "Driving for Dollars", "PPC", "SEO", "Social Media", "List Import", "API", "Other"] },
      { key: "assignUser", label: "Opportunity owner", type: "select", options: ["MooN Estates", "Sandeep Kumar (Admin)", "Senior Advisor", "Sales Lead"] },
      { key: "description", label: "Deal notes", type: "textarea", table: false },
    ],
  },
  {
    key: "accounts",
    label: "Accounts",
    singular: "Account",
    path: "/accounts",
    endpoint: "account",
    icon: Landmark,
    group: "Workspace",
    addMany: true,
    fields: [
      { key: "name", label: "Account name", required: true },
      { key: "emailAddress", label: "Email", type: "email" },
      { key: "nonPrimaryEmail", label: "Secondary email", type: "email", table: false },
      { key: "officePhone", label: "Office phone", type: "phone" },
      { key: "alternatePhone", label: "Alternate phone", type: "phone", table: false },
      { key: "website", label: "Website", type: "url" },
      { key: "type", label: "Type", type: "select", options: ["Investor", "Buyer", "Seller", "Agency", "Vendor", "Partner", "Other"] },
      { key: "industry", label: "Industry" },
      { key: "ownership", label: "Ownership", table: false },
      { key: "billingStreet", label: "Billing address", type: "textarea", table: false },
      { key: "shippingStreet", label: "Shipping address", type: "textarea", table: false },
      { key: "assignUser", label: "Account owner", table: false },
      { key: "description", label: "Account notes", type: "textarea", table: false },
    ],
  },
  {
    key: "tasks",
    label: "Tasks",
    singular: "Task",
    path: "/tasks",
    endpoint: "task",
    icon: CheckSquare2,
    group: "Activity",
    fields: [
      { key: "title", label: "Title", required: true },
      { key: "category", label: "Category", type: "select", options: ["Follow-up", "Call", "Email", "Meeting", "Due Diligence", "Closing", "Administration"] },
      { key: "status", label: "Status", type: "select", options: ["todo", "in-progress", "complete"] },
      { key: "assignTo", label: "Assigned user" },
      { key: "assignToLead", label: "Related lead", table: false },
      { key: "start", label: "Starts", type: "datetime" },
      { key: "end", label: "Due", type: "datetime" },
      { key: "reminder", label: "Reminder", type: "datetime", table: false },
      { key: "allDay", label: "All-day task", type: "boolean", table: false },
      { key: "description", label: "Description", type: "textarea" },
      { key: "notes", label: "Internal notes", type: "textarea", table: false },
    ],
  },
  {
    key: "meetings",
    label: "Meetings",
    singular: "Meeting",
    path: "/meetings",
    endpoint: "meeting",
    icon: Video,
    group: "Activity",
    fields: [
      { key: "agenda", label: "Agenda", required: true },
      { key: "location", label: "Location" },
      { key: "dateTime", label: "Date and time", type: "datetime" },
      { key: "related", label: "Related record" },
      { key: "attendes", label: "Attendees", type: "textarea", table: false },
      { key: "attendesLead", label: "Lead attendees", type: "textarea", table: false },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "calls",
    label: "Calls",
    singular: "Call",
    path: "/calls",
    endpoint: "phoneCall",
    icon: Phone,
    group: "Activity",
    fields: [
      { key: "sender", label: "From", type: "phone", required: true },
      { key: "recipient", label: "To", type: "phone", required: true },
      { key: "callDuration", label: "Duration" },
      { key: "startDate", label: "Started", type: "datetime" },
      { key: "endDate", label: "Ended", type: "datetime" },
      { key: "createByLead", label: "Related lead", table: false },
      { key: "createByContact", label: "Related contact", table: false },
      { key: "callNotes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "emails",
    label: "Emails",
    singular: "Email",
    path: "/emails",
    endpoint: "email",
    icon: Mail,
    group: "Activity",
    fields: [
      { key: "sender", label: "Sender", type: "email", required: true },
      { key: "recipient", label: "Recipient", type: "email", required: true },
      { key: "subject", label: "Subject", required: true },
      { key: "message", label: "Message", type: "textarea" },
      { key: "html", label: "HTML content", type: "textarea", table: false },
      { key: "createByLead", label: "Related lead", table: false },
      { key: "createByContact", label: "Related contact", table: false },
    ],
  },
  {
    key: "calendar",
    label: "Calendar",
    singular: "Calendar event",
    path: "/calendar",
    endpoint: "calendar",
    icon: CalendarDays,
    group: "Activity",
    readOnly: true,
    fields: [
      { key: "title", label: "Event" },
      { key: "start", label: "Starts", type: "date" },
      { key: "end", label: "Ends", type: "date" },
      { key: "category", label: "Category" },
    ],
  },
  {
    key: "invoices",
    label: "Invoices",
    singular: "Invoice",
    path: "/invoices",
    endpoint: "invoices",
    icon: ReceiptText,
    group: "Operations",
    addMany: true,
    fields: [
      { key: "title", label: "Title", required: true },
      { key: "invoiceNumber", label: "Invoice number" },
      { key: "status", label: "Status", type: "select", options: ["Draft", "Sent", "Paid", "Overdue"] },
      { key: "grandTotal", label: "Total", type: "currency" },
      { key: "account", label: "Account" },
      { key: "contact", label: "Contact" },
      { key: "items", label: "Line items", type: "textarea", description: "JSON list of invoice line items.", table: false },
    ],
  },
  {
    key: "payments",
    label: "Payments",
    singular: "Payment",
    path: "/payments",
    endpoint: "payment",
    icon: BadgeIndianRupee,
    group: "Operations",
    readOnly: true,
    fields: [
      { key: "reference", label: "Reference" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "account", label: "Account" },
      { key: "contact", label: "Contact" },
      { key: "status", label: "Status" },
      { key: "createdDate", label: "Date", type: "date" },
    ],
  },
  {
    key: "documents",
    label: "Documents",
    singular: "Document",
    path: "/documents",
    endpoint: "document",
    icon: FolderKanban,
    group: "Operations",
    fields: [
      { key: "folderName", label: "Folder", required: true },
      { key: "files", label: "Files" },
      { key: "createdDate", label: "Created", type: "date" },
    ],
  },
  {
    key: "reports",
    label: "Reports",
    singular: "Report",
    path: "/reports",
    endpoint: "reporting",
    icon: BarChart3,
    group: "Operations",
    readOnly: true,
    fields: [
      { key: "name", label: "Report" },
      { key: "value", label: "Value" },
      { key: "period", label: "Period" },
    ],
  },
  {
    key: "email-templates",
    label: "Email templates",
    singular: "Email template",
    path: "/email-templates",
    endpoint: "email-temp",
    icon: MailOpen,
    group: "Operations",
    fields: [
      { key: "name", label: "Template name", required: true },
      { key: "subject", label: "Subject", required: true },
      { key: "html", label: "Content", type: "textarea", required: true },
    ],
  },
  {
    key: "users",
    label: "Users",
    singular: "User",
    path: "/users",
    endpoint: "user",
    icon: UsersRound,
    group: "Administration",
    adminOnly: true,
    fields: [
      { key: "username", label: "Email", type: "email", required: true },
      { key: "password", label: "Temporary password", type: "password", required: true, placeholder: "Minimum 8 characters", table: false },
      { key: "firstName", label: "First name", required: true },
      { key: "lastName", label: "Last name", required: true },
      { key: "phoneNumber", label: "Phone", type: "phone" },
      { key: "role", label: "Role", type: "select", options: ["user", "superAdmin"] },
    ],
  },
  {
    key: "roles",
    label: "Roles",
    singular: "Role",
    path: "/roles",
    endpoint: "role-access",
    icon: ShieldCheck,
    group: "Administration",
    adminOnly: true,
    fields: [
      { key: "roleName", label: "Role name", required: true },
      { key: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    key: "custom-fields",
    label: "Custom fields",
    singular: "Field module",
    path: "/custom-fields",
    endpoint: "custom-field",
    icon: SlidersHorizontal,
    group: "Administration",
    adminOnly: true,
    fields: [
      { key: "moduleName", label: "Module", required: true },
      { key: "fields", label: "Fields" },
      { key: "headings", label: "Headings" },
    ],
  },
  {
    key: "validation",
    label: "Validation",
    singular: "Validation rule",
    path: "/validation",
    endpoint: "validation",
    icon: FileCheck2,
    group: "Administration",
    adminOnly: true,
    fields: [
      { key: "name", label: "Name", required: true },
      { key: "value", label: "Value" },
      { key: "message", label: "Message", required: true },
    ],
  },
  {
    key: "table-fields",
    label: "Table fields",
    singular: "Table field",
    path: "/table-fields",
    endpoint: "custom-field",
    icon: Layers3,
    group: "Administration",
    adminOnly: true,
    readOnly: true,
    fields: [
      { key: "moduleName", label: "Module" },
      { key: "fields", label: "Visible fields" },
    ],
  },
  {
    key: "modules",
    label: "Modules",
    singular: "Module",
    path: "/modules",
    endpoint: "modules",
    icon: Layers3,
    group: "Administration",
    adminOnly: true,
    fields: [
      { key: "moduleName", label: "Module name", required: true },
      { key: "isActive", label: "Active", type: "select", options: ["true", "false"] },
    ],
  },
  {
    key: "images",
    label: "Brand assets",
    singular: "Brand asset",
    path: "/images",
    endpoint: "images",
    icon: Image,
    group: "Administration",
    adminOnly: true,
    readOnly: true,
    fields: [
      { key: "logoLgImg", label: "Large logo" },
      { key: "logoSmImg", label: "Small logo" },
      { key: "authImg", label: "Authentication image" },
    ],
  },
  {
    key: "integrations",
    label: "Integrations",
    singular: "Integration",
    path: "/integrations",
    endpoint: "integrations",
    icon: PlugZap,
    group: "Administration",
    adminOnly: true,
    readOnly: true,
    fields: [{ key: "provider", label: "Provider" }],
  },
  {
    key: "billing",
    label: "Billing",
    singular: "Subscription",
    path: "/billing",
    endpoint: "billing/subscription",
    icon: CreditCard,
    group: "Administration",
    adminOnly: true,
    readOnly: true,
    fields: [{ key: "status", label: "Subscription status" }],
  },
  {
    key: "settings",
    label: "Settings",
    singular: "Setting",
    path: "/settings",
    endpoint: "route",
    icon: Settings2,
    group: "Administration",
    adminOnly: true,
    readOnly: true,
    fields: [
      { key: "name", label: "Setting" },
      { key: "value", label: "Value" },
    ],
  },
]

export const moduleByPath = (path: string) => modules.find((item) => item.path === path)

export const legacyRedirects: Record<string, string> = {
  "/lead": "/leads",
  "/account": "/accounts",
  "/task": "/tasks",
  "/metting": "/meetings",
  "/phone-call": "/calls",
  "/email": "/emails",
  "/email-template": "/email-templates",
  "/calender": "/calendar",
  "/reporting-analytics": "/reports",
  "/user": "/users",
  "/custom-Fields": "/custom-fields",
  "/validations": "/validation",
  "/table-field": "/table-fields",
  "/active-deactive-module": "/modules",
  "/change-images": "/images",
  "/admin-setting": "/settings",
  "/default": "/",
}
